services:
  server:
    image:
      ml-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - CONFIG_PATH="../.env"
    volumes:
      - ./.env:/app/.env
    ports:
      - "8001:8001"
